### ISSUE TITLE
Updates stopped

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/biudzetas#3]
@povilasp did latest Pull Request broke updates mechanism? Changes #1 or #2 should not have impacted it, although it might be, that bot can't push to repository anymore, because it's branch does not have changes which are in remote. Fast forward might be needed. Can you please take a look at the server?

**Comment by povilasp** [comment]
added git pull --rebase, but the bot doesn't commit anything if there aren't any changes and we are quite updating everything this weekend, it might be so that there are actually no changes.
