### ISSUE TITLE
Problema su kabutėmis

### ISSUE THREAD

**Issue by palepal** [vilnius/biudzetas#4]
Argh, pagaliau išsiaiškinau:
Duomenyse kai kur yra kabutės kabutėse, todėl duomenys neteisingai suskaidomi.

Pvz.
"Kitos išlaidos KIS ,,Savivaldybė"" (beje, daug kur vienos kabutės atidaro, kitos uždaro pavadinimą)
" lopšelis-darželis "Lakštingala""

Dvigubas kabutes reikėtų escape'int dvigubom kabutėm:
"If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote"
https://tools.ietf.org/html/rfc4180

**Comment by povilasp** [comment]
problema pašalinta, biudžeto skriptai turėtų visi būt doublequoteinti
